language: node_js
node_js:
  - "8.10.0"
before_script:
  - lerna bootstrap --ignore-scripts
  - cd packages/easy-chameleon && rm -rf node_modules &&  npm i && cd ../../
  - cd packages/chameleon-tool && rm -rf node_modules && npm i && cd ../../
script:
  - npm run coverage
after_script:
  - cat coverage/lcov.info | node_modules/.bin/codecov
